### ISSUE TITLE
Specific WMS cannot be registered in RCS, works fine in other GIS applications

### ISSUE THREAD

**Issue by dan-bowerman** [fgpv-vpgf/rcs#52]
Capabilities doc: http://cabin.cciw.ca/cabin/cabin_ows.asp?VERSION=1.3.0&REQUEST=GetCapabilities&SERVICE=wms

Registration request:
`{
	"fr": {
		"feature_info_format": "text/plain",
		"service_url": "http://cabin.cciw.ca/cabin/cabin_ows.asp",
		"service_type": "ogcWms",
		"legend_format": "image/gif",
		"scrape_only": ["CABIN"],
		"service_name": "WMS french"
	},
	"en": {
		"feature_info_format": "text/plain",
		"service_url": "http://cabin.cciw.ca/cabin/cabin_ows.asp",
		"service_type": "ogcWms",
		"legend_format": "image/gif",
		"scrape_only": ["CABIN"],
		"service_name": "WMS english"
	},
	"version": "2.0"
}`

Returned data:

> 10.0.2.2 - - [16/Aug/2016 11:51:46] "PUT /v2/register/0 HTTP/1.1" 400 -
> INFO:werkzeug:10.0.2.2 - - [16/Aug/2016 11:51:46] "PUT /v2/register/0 HTTP/1.1" 400 -
> INFO:rcsaccesslog:10.0.2.2 PUT /v2/register/0 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
> DEBUG:rcsaccesslog:{
>         "fr": {
>                 "feature_info_format": "text/plain",
>                 "service_url": "http://cabin.cciw.ca/cabin/cabin_ows.asp?VERSION=1.3.0",
>                 "service_type": "ogcWms",
>                 "legend_format": "image/gif",
>                 "scrape_only": ["CABIN"],
>                 "service_name": "WMS french"
>         },
>         "en": {
>                 "feature_info_format": "text/plain",
>                 "service_url": "http://cabin.cciw.ca/cabin/cabin_ows.asp?VERSION=1.3.0",
>                 "service_type": "ogcWms",
>                 "legend_format": "image/gif",
>                 "scrape_only": ["CABIN"],
>                 "service_name": "WMS english"
>         },
>         "version": "2.0"
> }
> --------------------------------------------------------------------------------
> DEBUG in sigcheck [/vagrant/services/regparse/sigcheck.py:45]:
> Authorization: ibZkHR2UklzY55K1TdFYkqckfDaG_Sd05j-PGyzvhz8
> --------------------------------------------------------------------------------
> DEBUG:__main__:Authorization: ibZkHR2UklzY55K1TdFYkqckfDaG_Sd05j-PGyzvhz8
> --------------------------------------------------------------------------------
> DEBUG in sigcheck [/vagrant/services/regparse/sigcheck.py:45]:
> TimeStamp: 2016-08-16T11:54:36.298Z
> --------------------------------------------------------------------------------
> DEBUG:__main__:TimeStamp: 2016-08-16T11:54:36.298Z
> --------------------------------------------------------------------------------
> DEBUG in sigcheck [/vagrant/services/regparse/sigcheck.py:45]:
> Sender: jstest
> --------------------------------------------------------------------------------
> DEBUG:__main__:Sender: jstest
> --------------------------------------------------------------------------------
> INFO in sigcheck [/vagrant/services/regparse/sigcheck.py:59]:
> Signature received: ibZkHR2UklzY55K1TdFYkqckfDaG_Sd05j-PGyzvhz8  ##  Signature generated: ibZkHR2UklzY55K1TdFYkqckfDaG_Sd05j-PGyzvhz8
> --------------------------------------------------------------------------------
> INFO:__main__:Signature received: ibZkHR2UklzY55K1TdFYkqckfDaG_Sd05j-PGyzvhz8  ##  Signature generated: ibZkHR2UklzY55K1TdFYkqckfDaG_Sd05j-PGyzvhz8
> --------------------------------------------------------------------------------
> INFO in sigcheck [/vagrant/services/regparse/sigcheck.py:108]:
> Header date: 2016-08-16T11:54:36.298Z  ##  Current timestamp: 2016-08-16 11:54:35.930768+00:00
> --------------------------------------------------------------------------------
> INFO:__main__:Header date: 2016-08-16T11:54:36.298Z  ##  Current timestamp: 2016-08-16 11:54:35.930768+00:00
> 200
> {'content-encoding': 'gzip', 'transfer-encoding': 'chunked', 'set-cookie': 'ASPSESSIONIDCADTQQRD=BHKJFHPAPBNOCIAINPALCFBN; path=/', 'x-powered-by': 'ASP.NET', 'vary': 'Accept-Encoding', 'server': 'Microsoft-IIS/7.5', 'cache-control': 'private', 'date': 'Tue, 16 Aug 2016 11:55:50 GMT', 'content-type': 'text/html'}
> --------------------------------------------------------------------------------
> WARNING in registration [/vagrant/services/registration.py:92]:
> Problem reading service endpoints
> --------------------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/vagrant/services/registration.py", line 87, in put
>     v2_node, v1_node = regparse.make_node(key, req, current_app.config)
>   File "/vagrant/services/regparse/universal.py", line 108, in make_node
>     for lang in langs}
>   File "/vagrant/services/regparse/universal.py", line 108, in <dictcomp>
>     for lang in langs}
>   File "/vagrant/services/regparse/universal.py", line 84, in get_endpoint_type
>     raise ServiceEndpointException('Endpoint({0}) did not match any known service type'.format(endpoint))
> ServiceEndpointException: ServiceEndpointException Endpoint(http://cabin.cciw.ca/cabin/cabin_ows.asp?VERSION=1.3.0) did not match any known service type
> WARNING:__main__:Problem reading service endpoints
> Traceback (most recent call last):
>   File "/vagrant/services/registration.py", line 87, in put
>     v2_node, v1_node = regparse.make_node(key, req, current_app.config)
>   File "/vagrant/services/regparse/universal.py", line 108, in make_node
>     for lang in langs}
>   File "/vagrant/services/regparse/universal.py", line 108, in <dictcomp>
>     for lang in langs}
>   File "/vagrant/services/regparse/universal.py", line 84, in get_endpoint_type
>     raise ServiceEndpointException('Endpoint({0}) did not match any known service type'.format(endpoint))
> ServiceEndpointException: ServiceEndpointException Endpoint(http://cabin.cciw.ca/cabin/cabin_ows.asp?VERSION=1.3.0) did not match any known service type
> --------------------------------------------------------------------------------
> ERROR in utils [/vagrant/services/utils.py:28]:

**Comment by dan-bowerman** [comment]
Long story, short with this one: the headers coming back with the GetCapabilities are returning as HTML instead of XML. The XML itself is fine, but until the headers for the service are remedied, we won't be able to register this service or use it in RAMP. 

This threw me for a bit at first because the WMS worked in several other applications that consumed WMS, they are apparently more forgiving of the data type coming back to them (it is XML, just being returned as HTML). I have spoken with the Data Catalogue clients requesting the ability to register this WMS, as well as the CABIN site administrator (my former supervisor), and he is looking into having this remedied on his end. Once this is complete, we should have no problem consuming this.

We probably should not be in the business of creating workarounds for misconfigured services, but a technical solution for this would be to remove strict XML validation when registering a service. I'm considering this issue closed.
